apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configmap.yaml
  - ./appconfig.yaml
replacements:
  - source:
      kind: AppConfig
      name: myappconfig
      fieldPath: .
    targets:
      - select:
          kind: ConfigMap
          name: myconfigmap
        fieldPaths:
          - .data.config\.yaml
        options:
          create: true
